# Generated by Django 4.1.5 on 2023-01-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
