# Generated by Django 4.1.5 on 2023-01-08 06:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(default="test:"),
            preserve_default=False,
        ),
    ]
