# Generated by Django 4.1.5 on 2023-01-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_post_overview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="overview", field=models.TextField(),
        ),
    ]
