# Generated by Django 4.1.5 on 2023-01-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="content", field=models.TextField(),
        ),
    ]
